### ISSUE TITLE
ReadMe Description

### ISSUE THREAD

**Issue by sadaqatullahn** [markkimsal/statsd-elasticsearch-backend#22]
This is a request to please make documentation easier or suggest a tutorial for configurations. I am new to this and cannot find any good place to learn from except for reading the code directly.

**Comment by markkimsal** [comment]
The defaults should just work out of the box, unless you are using ES 2.0.  There is a pull request for making ES 2.0 work out of the box.

Is anything not working or is it just confusing?

Using ES as a data store for statsd is not the optimal solution.  The metric name mapping is a kludge and the whole process works better with something like graphite ( http://matt.aimonetti.net/posts/2013/06/26/practical-guide-to-graphite-monitoring/ ).  But, if you have an ES installation and don't want to maintain too many systems you can store statsd information into ES.

**Comment by markkimsal** [comment]
Basically, statsd will compute stats on regular intervals from your apps and send the data to any backend in the following format:

    accounts.authentication.password.failed:1|c

If your app is sending a continuous stream of password failures of 1 per second for an entire minute, statsd will tally up the counters and send the backend compiled information only when it is configured to flush.  So your backend DB will get 6 packets over 1 minute of

    accounts.authentication.password.failed:10|c

if your flush time is 10 seconds.

When you store the info into graphite you can perform queries at ANY dotted segment of the key.

    accounts.authentication.password.*
    *.*.*.failed

You can't query like that in ES.  ES stores in key value pairs.  So, you have to decide on a naming convention when you start.  The format is entirely up to you.  That's why there are pluggable formatters to translate what is inherently a tree structure into key/value pairs.

**Comment by sadaqatullahn** [comment]
Thanks for an amazing reply.
I was working on Nagios Plugin for Gunicorn. Although the work is done, it took me more than 20 days to finish because I got confused with non-detailed documentation. But I was an amazing ride. I learnt a lot from your code. Specially the communication between two applications.

If you want to look at my plugin, visit the following link:
https://github.com/sadaqatullahn/check_gunicorn
